// Generated by CoffeeScript 1.9.3
(function() {
  var app;

  app = angular.module('app', ['ngRoute']);

  app.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/', {
        templateUrl: 'partials/info.html',
        controller: 'InfoController'
      }).when('/:sha', {
        templateUrl: 'partials/summoner-list.html',
        controller: 'TwitchUserController'
      }).when('/:sha/:summonerID', {
        templateUrl: 'partials/summoner-detail.html',
        controller: 'SummonerDetailController'
      }).otherwise({
        redirectTo: '/'
      });
    }
  ]);

  app.factory('apiService', function($http, $httpParamSerializer) {
    var apiUrl;
    apiUrl = 'http://127.0.0.1:8001/';
    return {
      getTwitchUser: function(sha) {
        return $http.get(apiUrl + 'user/' + sha).then(function(response) {
          return response.data;
        });
      },
      getSummoner: function(sha, summonerID) {
        return $http.get(apiUrl + 'user/' + sha + '/summoner/' + summonerID).then(function(response) {
          return response.data;
        });
      },
      unlinkSummoner: function(sha, summonerID) {
        var data;
        data = {
          sha: sha,
          summoner_id: summonerID
        };
        data = $httpParamSerializer(data);
        return $http.post(apiUrl + 'unlink', data, {
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
          }
        }).then(function(response) {
          return response.data;
        });
      }
    };
  });

  app.controller('TwitchUserController', function(apiService, $routeParams, $scope, $log) {
    $scope.sha = $routeParams.sha;
    $scope.unlink = function(summonerID) {
      if ($scope.twitchName) {
        return apiService.unlinkSummoner($scope.sha, summonerID).then(function() {
          return $log.info('unlinked');
        });
      }
    };
    return apiService.getTwitchUser($scope.sha).then(function(data) {
      $scope.twitchName = data.name;
      return $scope.summoners = data.summoners;
    });
  });

  app.controller('InfoController', function($scope, $log) {
    return $scope.info = "INFO";
  });

  app.controller('SummonerDetailController', function(apiService, $routeParams, $scope, $log) {
    $scope.sha = $routeParams.sha;
    return apiService.getSummoner($scope.sha, $routeParams.summonerID).then(function(data) {
      $scope.twitchName = data.name;
      return $scope.summoner = data.summoner;
    });
  });

}).call(this);

//# sourceMappingURL=app.js.map
